version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
        environment:
          - NODE_ENV: TEST
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn versions
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint all source files
          command: yarn lint
      - run:
          name: Build all libs and package binaries
          command: yarn build
